def get_merge_prompt(task, worker_outputs: list[str]):
    return f"""
    Your objective is to merge the outputs of several independent worker agents into a single, cohesive, and comprehensive final response.

    You will receive the original <task> and the corresponding result.

    Crucial Context: The worker agents operated in strict parallel. They were blind to the <task> and blind to each other's work. It is YOUR job to bridge their findings and format them for the end user.

    You must adhere strictly to the following synthesis rules:

    ## 1. Master Task Alignment (The Prime Directive)
    - Read the <task> carefully. The user only cares about this goal.
    - Extract ONLY the information from the <worker_outputs> that directly serves the <task>. 
    - Ruthlessly discard irrelevant tangents, filler text, or meta-commentary generated by the workers.

    ## 2. Cohesion and Deduplication
    - DO NOT simply concatenate the worker outputs. You must rewrite and weave the information into a single unified narrative or logical structure.
    - Workers likely found overlapping information. Deduplicate all repeated facts or arguments. The final output must read as if it were written by a single expert.

    ## 3. Conflict Resolution
    - If workers provide contradictory data or conflicting arguments, DO NOT hallucinate a compromise. 
    - Explicitly acknowledge the discrepancy in the final output (e.g., "Sources differ on this metric: [Source A] indicates X, while [Source B] suggests Y").

    ## 4. Formatting and Tone
    - Structure the final response logically using professional Markdown formatting (Headers, bullet points, bold text for emphasis).
    - Do not reference the "workers", "sub-tasks", or the "system" in your output. Present the information directly to the user as a finalized artifact.

    Synthesize the data and provide the final response.
    
    <task>: {task}
    
    <worker_outputs>: {'\n\n'.join(worker_outputs)}
"""